version: "3"

services:

  db:
    container_name: db
    image: mariadb/server:10.2
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306

  adminer:
    container_name: adminer-integration
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: mariadb-integration
      ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
    ports:
      - 8080:8080
